name: Linux C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make all -C 3_Implementation/
    - name: Install cppcheck
      run: sudo apt-get -y install cppcheck
    - name: Cppcheck code
      run: cppcheck /3_Implementation project_main.c
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make test
      run: |
        make all -C 3_Implemntation/
        make test -C 3_Implementation/
        make leak -C 3_Implementation/
