name: Linux C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make all -C 3_Implementation/

      - name: test
        run: make test -C 3_Implementation/

      - name: apt install dependency
        run: |
          sudo apt-get -y install valgrind
          sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
      - name: make test
        run: make leak -C 3_Implementation/
