name: Linux C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make all -C Periodic-Table/3_Implementation/
    - name: Run
      run: make run -C Periodic-Table/3_Implementation/
    - name: Test Case
      run: make test -C Periodic-Table/3_Implementation/
    - name: Memory leak
      run: make leak -C Periodic-Table/3_Implementation/
