name: Linux C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make
    - name: Run
      run: make run
    - name: Test Case
      run: make test
    - name: Memory leak
      run: make leak
